### ISSUE TITLE
test failures with 0.8.13

### ISSUE THREAD

**Issue by Apteryks** [google/zerocopy#2143] opened 2024-12-10 09:20 UTC
Hello,

After updating rust-zerocopy in Guix to version 0.8.13, I see these test failures:

```
test util::tests::test_round_down_to_next_multiple_of_alignment_zerocopy_panic_in_const_and_vec_try_reserve - should panic ... FAILED
test util::tests::test_round_down_to_next_multiple_of_alignment ... ok
test wrappers::tests::test_maybe_uninit ... ok
test layout::tests::test_validate_cast_and_convert_metadata ... FAILED

failures:

---- error::tests::alignment_display stdout ----
thread 'error::tests::alignment_display' panicked at src/error.rs:1017:9:
assertion `left == right` failed
  left: "The conversion failed because the address of the source is not a multiple of the alignment of the destination type."
 right: "The conversion failed because the address of the source is not a multiple of the alignment of the destination type.\n\nSource type: &[u8]\nSource address: 0x7ffff70d7401 (a multiple of 1)\nDestination type: elain::Align<8>\nDestination alignment: 8"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- error::tests::validity_display stdout ----
thread 'error::tests::validity_display' panicked at src/error.rs:1082:9:
assertion `left == right` failed
  left: "The conversion failed because the source bytes are not a valid value of the destination type."
 right: "The conversion failed because the source bytes are not a valid value of the destination type.\n\nDestination type: bool"

---- error::tests::size_display stdout ----
thread 'error::tests::size_display' panicked at src/error.rs:1062:9:
assertion `left == right` failed
  left: "The conversion failed because the source was incorrectly sized to complete the conversion into the destination type."
 right: "The conversion failed because the source was incorrectly sized to complete the conversion into the destination type.\n\nSource type: &[u8]\nSource size: 2 bytes\nDestination type: [u8]"

---- util::tests::test_round_down_to_next_multiple_of_alignment_zerocopy_panic_in_const_and_vec_try_reserve stdout ----
note: test did not panic as expected
---- layout::tests::test_validate_cast_and_convert_metadata stdout ----
thread 'layout::tests::test_validate_cast_and_convert_metadata' panicked at src/layout.rs:974:9:
layout(Sized { size: 0 }, 1).validate_cast_and_convert_metadata(18446744073709551615, 1, Prefix)


failures:
    error::tests::alignment_display
    error::tests::size_display
    error::tests::validity_display
    layout::tests::test_validate_cast_and_convert_metadata
    util::tests::test_round_down_to_next_multiple_of_alignment_zerocopy_panic_in_const_and_vec_try_reserve

test result: FAILED. 74 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--lib`
error: in phase 'check': uncaught exception:
%exception #<&invoke-error program: "cargo" arguments: ("test" "--release") exit-status: 101 term-signal: #f stop-signal: #f> 
phase `check' failed after 9.1 seconds
command "cargo" "test" "--release" failed with status 101
build process 18 exited with status 256
builder for `/gnu/store/ydicww1w8fmh2d8p6nlfd9hd827zdpbp-rust-zerocopy-0.8.13.drv' failed with exit code 1
build of /gnu/store/ydicww1w8fmh2d8p6nlfd9hd827zdpbp-rust-zerocopy-0.8.13.drv failed
View build log at '/var/log/guix/drvs/yd/icww1w8fmh2d8p6nlfd9hd827zdpbp-rust-zerocopy-0.8.13.drv'.
```

Rust is at version 1.77.0.

**Comment by joshlf** [comment] 2024-12-10 15:41
Thanks for the report!

What OS and CPU architecture are you running on?

**Comment by joshlf** [comment] 2024-12-10 16:33
Update: I'm able to reproduce this locally by disabling `--cfg debug_assertions` when testing by adding the following to `Cargo.toml`:

```toml
[profile.test]
debug-assertions = false
```

Have you recently changed your CI to disable `debug_assertions` when testing?

**Comment by joshlf** [comment] 2024-12-10 16:40
I'm going to close this since, as far as I can tell, this isn't a bug on our side. Our tests are provided on a best-effort basis for others to run outside of our own CI infrastructure, so we don't consider this a breaking change. Feel free to continue the conversation here, of course.

**Closed by joshlf** 2024-12-10 16:40 UTC

**Comment by Apteryks** [comment] 2024-12-11 00:23
> Have you recently changed your CI to disable `debug_assertions` when testing?

No! We don't typically change any options when building crates in GNU Guix.  Perhaps the default value changed in recent Rust versions (this build was using 1.77.0 or perhaps even 1.82.0, I'd have to re-run it to make sure).

**Comment by joshlf** [comment] 2024-12-11 01:04
Can you link us to your CI configuration, and point out which job failed?

**Comment by Apteryks** [comment] 2024-12-11 02:51
I do not have a CI configuration to share; all the build logic is encapsulated in the GNU Guix tooling for Rust (its `cargo-build-system`).  What it does is basically take all the transitive sources referred by the package and its dependencies, unpack them as vendored source, which are referred via this created `.cargo/config` file:

```
[source.crates-io]
replace-with = 'vendored-sources'

[source.vendored-sources]
directory = 'guix-vendor'
```

and then build the package with `cargo build --release` and tested with `cargo test --release`, basically.

**Comment by Apteryks** [comment] 2024-12-11 02:56
Here's a complete build log in case that's of interest: [rust-zerocopy-0.8.13-test-failures.log.txt](https://github.com/user-attachments/files/18088862/rust-zerocopy-0.8.13-test-failures.log.txt)

**Comment by joshlf** [comment] 2024-12-11 16:47
It looks like you're building tests in release mode rather than debug mode (which is the default for `cargo test`):

```text
starting phase `check'
   Compiling serde v1.0.197
   Compiling proc-macro2 v1.0.79
   Compiling unicode-ident v1.0.12
   Compiling hashbrown v0.14.3
   Compiling equivalent v1.0.1
   Compiling winnow v0.6.5
   Compiling serde_json v1.0.114
   Compiling ryu v1.0.15
   Compiling rustversion v1.0.14
   Compiling itoa v1.0.11
   Compiling trybuild v1.0.91
   Compiling rand_core v0.6.4
   Compiling either v1.10.0
   Compiling termcolor v1.4.0
   Compiling glob v0.3.1
   Compiling dissimilar v1.0.2
   Compiling once_cell v1.19.0
   Compiling static_assertions v1.1.0
   Compiling elain v0.3.0
   Compiling rand v0.8.5
   Compiling itertools v0.11.0
   Compiling quote v1.0.35
   Compiling indexmap v2.2.5
   Compiling syn v2.0.48
   Compiling serde_spanned v0.6.5
   Compiling toml_datetime v0.6.5
   Compiling toml_edit v0.22.9
   Compiling serde_derive v1.0.197
   Compiling zerocopy-derive v0.8.13
   Compiling toml v0.8.12
   Compiling zerocopy v0.8.13 (/tmp/guix-build-rust-zerocopy-0.8.13.drv-0/zerocopy-0.8.13)
    Finished release [optimized] target(s) in 10.87s
     Running unittests src/lib.rs (target/release/deps/zerocopy-e379c1f6cbfbdb38)
```

See "release" on the last two lines.

By default, compiling in release mode also disables `debug_assertions`. I'm not sure *how* it changed to compile in release mode, but I'm 99% sure that's the culprit of the test failures you're seeing.

**Comment by Apteryks** [comment] 2024-12-13 04:36
Uh; the `cargo-build-system` in Guix currently uses `--release` as a default test flag, since test-flags were introduced in Guix commit 1d3acde5087d50af6a4901fd7614f0940eb7b41d in 2019.  It seems to have been simply copied from the pre-existing `cargo-build-flags`; I'll send a patch to Guix suggesting to remove the flag.

**Comment by Apteryks** [comment] 2024-12-13 04:37
Thanks a lot for your help/investigation!

**Comment by joshlf** [comment] 2024-12-13 16:12
> Uh; the `cargo-build-system` in Guix currently uses `--release` as a default test flag, since test-flags were introduced in Guix commit 1d3acde5087d50af6a4901fd7614f0940eb7b41d in 2019. It seems to have been simply copied from the pre-existing `cargo-build-flags`; I'll send a patch to Guix suggesting to remove the flag.

Weird, no clue why it's just started to fail now. I wonder if perhaps the previous zerocopy version used was older than 0.8.12 and was far enough back that we didn't have these tests? Dunno.

Anyway, glad we figured out something that should unblock you!

**Comment by Apteryks** [comment] 2024-12-19 02:38
For the record, the outcome of this conversation on the Guix is is here: https://issues.guix.gnu.org/74958

Thanks for pinpointing the issue (the use of `--release` flag for running `cargo test`).
