### ISSUE TITLE
Easier splitting for types containing slice DSTs

### ISSUE THREAD

**Issue by valaphee** [google/zerocopy#2001] opened 2024-11-01 10:58 UTC
While working on file system drivers for a custom operating system, I'm using buffers, which basically consist of multiple entries. Each entry contains a slice DST, but it's not possible to store them as slice itself, which is why I need to split them up.

One entry might look like:
```rs
#[repr(C)]
#[derive(Debug, FromBytes, Immutable, KnownLayout)]
pub struct Entry {
    pub index: u64,
    pub name_length: u8,
    pub name: [u8],
}
```
where the first entry's name has the full length of the buffer.

And are split up by
```rs
let buffer_align = align_of_val(&mut buffer);
let Ok(next_buffer) = Entry::try_mut_from_bytes(
    &mut buffer.name[(buffer.name_length as usize)..].align(buffer_align),
) else {
    break;
};
buffer = next_buffer;
```
but requires some boilerplate. (and also a align method, which aligns the pointer)

The compiler will probably figure out the alignment at compile-time and optimize out the alignment check. But it's better to use the already known layout information.

**Comment by joshlf** [comment] 2024-11-04 21:27
For the length, we already have this tracked in #1289. Can you confirm that that issue would support your use case?

Also, can you clarify what `.align` does here? I'm not sure what method that refers to.

```rust
    &mut buffer.name[(buffer.name_length as usize)..].align(buffer_align),
```

**Comment by valaphee** [comment] 2024-11-05 23:09
In my example, `Entry` has to be aligned. I'm getting the end of the name, and align it to the next 8-byte boundary, to read the next `Entry`. (The `align` method just takes the ptr, and aligns it, and corrects the length)

#1289 would be helpful.

**Comment by joshlf** [comment] 2024-11-05 23:20
Okay, in that case I'm going to close this as a duplicate of #1289. Feel free to continue the conversation if you have more questions!

**Closed by joshlf** 2024-11-05 23:20 UTC
Labels: customer-request
